import { indexedPick } from "../utils/arrays";

export const proverbs: string[] = [
    "Check your checks (A check chases the King away)",
    "Squeeze (and hisshi) first, check later",
    "Defend the King with three generals",
    "Don't put King and Rook close together",
    "Move King and Rook to opposite sides",
    "Don't put the King on the Bishop's diagonal",
    "Early escape is worth eight moves",
    "Aim at the King's ears",
    "Approach the King by surrounding him",
    "Cut off the King's escape route",
    "Drive the King to the back rank",
    "Drop a silver at the King's belly",
    "Avoid a sitting King (A sitting King is a sitting duck)",
    "Against a sitting King, The Bishop is stronger than The Rook",
    "Against a king on edge, push edge pawn",
    "Against king on first rank, rook on second",
    "A Pawn is worth a thousand generals",
    "A double Pawn is worth a thousand generals (from the cartoon 'Tokin no Shoo-chan' by Jinbo Atsushi)",
    "With three Pawns in hand, a joining Pawns attack or an edge attack",
    "Without Pawns (in hand) the game is lost",
    "If there is mate with a Pawn drop, there is a legal mate too",
    "Start the fight with a Pawn sacrifice",
    "If you don't have a move, push the edge Pawn",
    "There is always a move at the edge",
    "Take two for one, even if there is a Pawn in it",
    "A tokin is faster than you think",
    "A tokin on 5c cannot lose",
    "Exchanging the Rook Pawn has three advantages",
    "A Pawn-anchored Gold is more solid than a rock",
    "Against a Silver in front of its Pawns, defend with a Pawn",
    "Silver in front of its Pawns - quick attack, Gold behind its Pawns - slow game",
    "To take the side-pawn is to grasp the nettle (obs.)",
    "Just take the side-pawn!",
    "In the Bishop Exchange, don't push the central Pawn",
    "A Vanguard Pawn is difficult to maintain (lit. The court noble cannot live up to his rank)",
    "The 5e Vanguard Pawn is the Tenno Mountain",
    "Recapture the Vanguard Pawn with the opposing Pawn",
    "Against the Mino play an edge attack",
    "Against the Yagura, joining Pawns attack",
    "Drop a Pawn on focal point",
    "The Knight that jumps high falls prey to a Pawn",
    "Drop the Knight well back",
    "With three Knights in hand, there must be a mate",
    "Drop the Lance on the back rank",
    "Drop the Lance at a distance",
    "Without Gold in hand there is no defence",
    "Save the Gold till the end (for the coup de grace)",
    "Entice the Gold diagonally forwards",
    "With Gold and Silver reversed (Gold above Silver), you're bound to get trouble",
    "With a Gold on your back rank, you can sacrifice the Rook",
    "Use the Silver like a plover (moving zig-zag)",
    "Mend the wall Silver",
    "Silver at the head of the (opponent's) Knight is the standard move",
    "Defend against major pieces by drawing them closer",
    "Don't be afraid to sacrifice major pieces",
    "Don't be afraid to sacrifice Rook or Bishop",
    "In the opening the Bishop is stronger than the Rook",
    "The Dragon to the enemy camp, the Horse to your own",
    "The sideways action of the Rook is strong in defence",
    "Rook and King are weak at the ears",
    "The Rook's page is the Silver",
    "Against Ranging Rook, aim at a Bishop's exchange",
    "Oppose Bishop with Bishop",
    "With a watchtower Bishop there is bound to be a brilliant move",
    "In a slow game the Bishop has the leading part",
];

export interface Proverb {
    number: number,
    text: string,
}

export function getRandomProverb(): Proverb {
    const pick = indexedPick(proverbs);

    return {
        number: pick.index + 1,
        text: pick.element,
    };
}